/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package conquistadores;

import conquistadores.Game;

/**
 *
 * @author OTVS
 */
public class FrameOptions extends javax.swing.JFrame {

    /**
     * Creates new form FrameOptions
     */
    public FrameOptions() {
        initComponents();
        modifyInitComponents();
    }

    /**
     * Modify the components after init to set the options to their latest
     * value.
     */
    private void modifyInitComponents() {
        switch (Game.BOARD_SIZE) {
            case 5:
                jRadioButtonBoardSize1.setSelected(true);
                break;
            case 7:
                jRadioButtonBoardSize2.setSelected(true);
                break;
            case 9:
                jRadioButtonBoardSize3.setSelected(true);
                break;
            case 11:
                jRadioButtonBoardSize4.setSelected(true);
                break;
            default:
                break;
        }
        switch (Game.PLACEMENT) {
            case 0:
                jRadioButtonPlacement1.setSelected(true);
                break;
            case 1:
                jRadioButtonPlacement2.setSelected(true);
                break;
            default:
                break;
        }
        switch (Game.GROUND_TYPE) {
            case 1:
                jRadioButtonGround1.setSelected(true);
                break;
            case 2:
                jRadioButtonGround2.setSelected(true);
                break;
            default:
                break;
        }
        System.out.println("Name:" + Game.GM.getPlayerName());
        j_PlayerName.setText(Game.GM.getPlayerName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jRadioButtonPlacement1 = new javax.swing.JRadioButton();
        jRadioButtonPlacement2 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jRadioButtonBoardSize1 = new javax.swing.JRadioButton();
        jRadioButtonBoardSize3 = new javax.swing.JRadioButton();
        jRadioButtonBoardSize2 = new javax.swing.JRadioButton();
        jRadioButtonBoardSize4 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        j_MaxActionsPerTurn = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jRadioButtonGround1 = new javax.swing.JRadioButton();
        jRadioButtonGround2 = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        j_PlayerName = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Difficulty");

        buttonGroup4.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Easy");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Initial Placement");

        buttonGroup1.add(jRadioButtonPlacement1);
        jRadioButtonPlacement1.setSelected(true);
        jRadioButtonPlacement1.setText("Random");
        jRadioButtonPlacement1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonPlacement1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonPlacement2);
        jRadioButtonPlacement2.setText("Normal");
        jRadioButtonPlacement2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonPlacement2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Board size");

        buttonGroup3.add(jRadioButtonBoardSize1);
        jRadioButtonBoardSize1.setText("5");
        jRadioButtonBoardSize1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonBoardSize1ActionPerformed(evt);
            }
        });

        buttonGroup3.add(jRadioButtonBoardSize3);
        jRadioButtonBoardSize3.setText("9");
        jRadioButtonBoardSize3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonBoardSize3ActionPerformed(evt);
            }
        });

        buttonGroup3.add(jRadioButtonBoardSize2);
        jRadioButtonBoardSize2.setText("7");
        jRadioButtonBoardSize2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonBoardSize2ActionPerformed(evt);
            }
        });

        buttonGroup3.add(jRadioButtonBoardSize4);
        jRadioButtonBoardSize4.setText("11");
        jRadioButtonBoardSize4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonBoardSize4ActionPerformed(evt);
            }
        });

        jLabel5.setText("Max actions per turn");

        jLabel6.setText("Max troops per case");

        jLabel7.setText("Initial troops Natives");

        j_MaxActionsPerTurn.setText("5");
        j_MaxActionsPerTurn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j_MaxActionsPerTurnActionPerformed(evt);
            }
        });

        jTextField2.setText("15");

        jTextField3.setText("5");

        jLabel8.setText("Initial troops Player");

        jTextField4.setText("5");

        jButton1.setText("JOUER");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel9.setText("Ground type");

        buttonGroup2.add(jRadioButtonGround1);
        jRadioButtonGround1.setSelected(true);
        jRadioButtonGround1.setText("Dark Gray");
        jRadioButtonGround1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonGround1ActionPerformed(evt);
            }
        });

        buttonGroup2.add(jRadioButtonGround2);
        jRadioButtonGround2.setText("Plain, Forest, Mountain");
        jRadioButtonGround2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonGround2ActionPerformed(evt);
            }
        });

        jLabel10.setText("Quel est votre nom ? ");

        jLabel11.setText("Not Used");

        jLabel12.setText("Vous arrivez sur un continent inexploré. Vous allez devoir vous battre");

        jLabel13.setText("pour conquérir le territoire. ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addGap(18, 18, 18)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(18, 18, 18)
                                    .addComponent(j_MaxActionsPerTurn, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(27, 27, 27)
                                    .addComponent(jLabel8)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(17, 17, 17)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel11)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel9)
                                        .addComponent(jLabel2))
                                    .addGap(36, 36, 36)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jRadioButtonPlacement1)
                                            .addGap(18, 18, 18)
                                            .addComponent(jRadioButtonPlacement2))
                                        .addComponent(jRadioButton1)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jRadioButtonGround1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jRadioButtonGround2))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jRadioButtonBoardSize1)
                                            .addGap(18, 18, 18)
                                            .addComponent(jRadioButtonBoardSize2)
                                            .addGap(18, 18, 18)
                                            .addComponent(jRadioButtonBoardSize3)
                                            .addGap(18, 18, 18)
                                            .addComponent(jRadioButtonBoardSize4)))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addGap(18, 18, 18)
                                    .addComponent(j_PlayerName, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton1))
                                .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jLabel10)
                    .addComponent(j_PlayerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jRadioButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonPlacement1)
                    .addComponent(jRadioButtonPlacement2)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonBoardSize3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jRadioButtonBoardSize1)
                        .addComponent(jRadioButtonBoardSize2)
                        .addComponent(jRadioButtonBoardSize4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonGround1)
                    .addComponent(jLabel9)
                    .addComponent(jRadioButtonGround2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(j_MaxActionsPerTurn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void j_MaxActionsPerTurnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j_MaxActionsPerTurnActionPerformed

    }//GEN-LAST:event_j_MaxActionsPerTurnActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        Game.AI_LEVEL = 0;
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButtonPlacement1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonPlacement1ActionPerformed
        Game.PLACEMENT = 0;
    }//GEN-LAST:event_jRadioButtonPlacement1ActionPerformed

    private void jRadioButtonPlacement2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonPlacement2ActionPerformed
        Game.PLACEMENT = 1;
    }//GEN-LAST:event_jRadioButtonPlacement2ActionPerformed

    private void jRadioButtonBoardSize1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonBoardSize1ActionPerformed
        Game.BOARD_SIZE = 5;
    }//GEN-LAST:event_jRadioButtonBoardSize1ActionPerformed

    private void jRadioButtonBoardSize2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonBoardSize2ActionPerformed
        Game.BOARD_SIZE = 7;
    }//GEN-LAST:event_jRadioButtonBoardSize2ActionPerformed

    private void jRadioButtonBoardSize3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonBoardSize3ActionPerformed
        Game.BOARD_SIZE = 9;
    }//GEN-LAST:event_jRadioButtonBoardSize3ActionPerformed

    private void jRadioButtonBoardSize4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonBoardSize4ActionPerformed
        Game.BOARD_SIZE = 11;
    }//GEN-LAST:event_jRadioButtonBoardSize4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Game.GM.setPlayerName(j_PlayerName.getText());
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButtonGround1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonGround1ActionPerformed
        Game.GROUND_TYPE = 1;
    }//GEN-LAST:event_jRadioButtonGround1ActionPerformed

    private void jRadioButtonGround2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonGround2ActionPerformed
        Game.GROUND_TYPE = 2;
    }//GEN-LAST:event_jRadioButtonGround2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameOptions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButtonBoardSize1;
    private javax.swing.JRadioButton jRadioButtonBoardSize2;
    private javax.swing.JRadioButton jRadioButtonBoardSize3;
    private javax.swing.JRadioButton jRadioButtonBoardSize4;
    private javax.swing.JRadioButton jRadioButtonGround1;
    private javax.swing.JRadioButton jRadioButtonGround2;
    private javax.swing.JRadioButton jRadioButtonPlacement1;
    private javax.swing.JRadioButton jRadioButtonPlacement2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField j_MaxActionsPerTurn;
    private javax.swing.JTextField j_PlayerName;
    // End of variables declaration//GEN-END:variables
}
